class Autogenerated {
  bool? status;
  String? message;
  Player? player;

  Autogenerated({this.status, this.message, this.player});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    player =
        json['player'] != null ? new Player.fromJson(json['player']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.player != null) {
      data['player'] = this.player!.toJson();
    }
    return data;
  }
}

class Player {
  int? id;
  int? userId;
  String? fullname;
  String? location;
  String? skillLevel;
  String? rating;
  String? archive;
  String? playerImage;
  String? createdAt;
  String? updatedAt;
  List<Videos>? videos;

  Player(
      {this.id,
      this.userId,
      this.fullname,
      this.location,
      this.skillLevel,
      this.rating,
      this.archive,
      this.playerImage,
      this.createdAt,
      this.updatedAt,
      this.videos});

  Player.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    fullname = json['fullname'];
    location = json['location'];
    skillLevel = json['skill_level'];
    rating = json['rating'];
    archive = json['archive'];
    playerImage = json['player_image'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['videos'] != null) {
      videos = <Videos>[];
      json['videos'].forEach((v) {
        videos!.add(new Videos.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['fullname'] = this.fullname;
    data['location'] = this.location;
    data['skill_level'] = this.skillLevel;
    data['rating'] = this.rating;
    data['archive'] = this.archive;
    data['player_image'] = this.playerImage;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.videos != null) {
      data['videos'] = this.videos!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Videos {
  int? id;
  int? playerId;
  String? description;
  int? archive;
  String? videoUrl;
  String? createdAt;
  String? updatedAt;
  String? ratingCount;
  bool? isFavourite;

  Videos(
      {this.id,
      this.playerId,
      this.description,
      this.archive,
      this.videoUrl,
      this.createdAt,
      this.updatedAt,
      this.ratingCount,
      this.isFavourite});

  Videos.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    playerId = json['player_id'];
    description = json['description'];
    archive = json['archive'];
    videoUrl = json['video_url'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    ratingCount = json['rating_count'];
    isFavourite = json['is_favourite'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['player_id'] = this.playerId;
    data['description'] = this.description;
    data['archive'] = this.archive;
    data['video_url'] = this.videoUrl;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['rating_count'] = this.ratingCount;
    data['is_favourite'] = this.isFavourite;
    return data;
  }
}
